DROP TABLE IF EXISTS rp_stg_reservations;

CREATE TABLE rp_stg_reservations (
    hotel_id              INTEGER,
    source_system         TEXT,
    reservation_id        TEXT,
    reservation_status    TEXT,
    booking_date          DATE,
    cancellation_date     DATE,
    checkin_date          DATE,
    checkout_date         DATE,
    channel_raw           TEXT,
    segment_raw           TEXT,
    rate_plan             TEXT,
    board_code            TEXT,
    policy_name           TEXT,
    rooms_booked          INTEGER,
    stay_nights           INTEGER,
    room_daily_price      NUMERIC,
    adults                INTEGER,
    teens                 INTEGER,
    children              INTEGER,
    guest_count           INTEGER,
    room_revenue          NUMERIC,
    city_tax_amount       NUMERIC,
    extras_amount         NUMERIC,
    total_amount          NUMERIC,
    paid_amount           NUMERIC,
    guest_name            TEXT,
    guest_country         TEXT,
    room_type_code_list   TEXT,
    room_type_name_list   TEXT,
    room_name_list        TEXT,
    tags                  TEXT
);
